const en = { message: {
  tusListas: 'Your lists',
  nuevaLista: 'Add list',
  eliminarLocalStorage: 'Permanently delete all lists',
  pdf: 'Export to PDF',
  crearLista: 'Create a new list',
  crear: 'Create',
  cancelar: 'Cancel',
  nuevaTarea: 'New task',
  borrarLista: 'Delete list',
  borrarTarea: 'Delete task',
  verTodas: 'View all tasks',
  todasTareas: 'All tasks',
  cerrar: 'Close',
  eliminarListaVacia: 'Delete empty list?',
  eliminarVaciaTexto: 'The list is empty. Do you want to delete it?',
  footText: 'Task management project by Enrique Jiménez',
  github: 'My GitHub',
  nombreLista: 'List name',
  completada: 'Completed',
  noCompletada: 'Not completada',
}}
export default en
