const es ={ message: {
  tusListas: 'Tus listas',
  nuevaLista: 'Añadir lista',
  eliminarLocalStorage: 'Eliminar todas las listas permanentemente',
  pdf:'Exportar a pdf',
  crearLista: 'Crea una nueva lista',
  crear: 'Crear',
  cancelar: 'Cancelar',
  nuevaTarea: 'Nueva Tarea',
  borrarLista: 'Borrar Lista',
  borrarTarea: 'Borrar Tarea',
  verTodas: 'Ver todas las tareas',
  todasTareas: 'Todas las tareas',
  cerrar: 'Cerrar',
  eliminarListaVacia: '¿Eliminar lista vacía?',
  eliminarVaciaTexto: 'La lista está vacía. ¿Quieres eliminarla?',
  footText:'Proyecto de gestión de tareas desarrolado por Enrique Jiménez',
  github: 'Mi github',
  nombreLista: 'Nombre de la lista',
  completada: 'Completada',
  noCompletada: 'No completada',
  excel: 'Exportar a Excel',
  csv: 'Exportar a CSV',
  si: 'Si',
  no: 'No',
  exportar: 'Exportar',
}}
export default es

