const gl = { message: {
  tusListas: 'As túas listas',
  nuevaLista: 'Engadir lista',
  eliminarLocalStorage: 'Eliminar todas as listas permanentemente',
  pdf: 'Exportar a PDF',
  crearLista: 'Crear unha nova lista',
  crear: 'Crear',
  cancelar: 'Cancelar',
  nuevaTarea: 'Nova tarefa',
  borrarLista: 'Eliminar lista',
  borrarTarea: 'Eliminar tarefa',
  verTodas: 'Ver todas as tarefas',
  todasTareas: 'Todas as tarefas',
  cerrar: 'Pechar',
  eliminarListaVacia: 'Eliminar lista baleira?',
  eliminarVaciaTexto: 'A lista está baleira. Queres eliminala?',
  footText: 'Proxecto de xestión de tarefas desenvolvido por Enrique Jiménez',
  github: 'O meu GitHub',
  nombreLista: 'Nome da lista',
  completada: 'Completada',
  noCompletada: 'Non completada',
  excel: 'Exportar a Excel',
  csv: 'Exportar a CSV',
  si: 'Si',
  no: 'Non',
  exportar: 'Exportar',
}}
export default gl
